apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: console-plugin
    app.kubernetes.io/created-by: cat-facts-operator
    app.kubernetes.io/instance: console-plugin
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: console-plugin-cluster-rolebinding
    app.kubernetes.io/part-of: cat-facts-operator
  name: cat-facts-operator-console-plugin-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cat-facts-operator-console-plugin-cluster-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: cat-facts-operator
