apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: cat-facts-console-plugin
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cat-facts-console-plugin
    app.kubernetes.io/part-of: cat-facts-console-plugin
    helm.sh/chart: openshift-console-plugin-0.1.0
  name: cat-facts-console-plugin-patcher
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - consoles
  verbs:
  - get
  - list
  - patch
  - update
