apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: test-cat-facts-operator
  namespace: openshift-marketplace
spec:
  displayName: Test Cat Facts Operator
  sourceType: grpc
  image: CATALOG_IMG
