---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - taco.moe
  resources:
  - catfacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - taco.moe
  resources:
  - catfacts/finalizers
  verbs:
  - update
- apiGroups:
  - taco.moe
  resources:
  - catfacts/status
  verbs:
  - get
  - patch
  - update
