apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-facts-console-plugin
  namespace: cat-facts-operator
  labels:
    app: cat-facts-console-plugin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat-facts-console-plugin
  template:
    metadata:
      labels:
        app: cat-facts-console-plugin
    spec:
      containers:
        - name: cat-facts-console-plugin
          image: quay.io/rymiller/cat-facts-console-plugin:latest
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - name: cat-facts-console-plugin-cert
              readOnly: true
              mountPath: /var/cert
      volumes:
        - name: cat-facts-console-plugin-cert
          secret:
            secretName: cat-facts-console-plugin-cert
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
